// Generated by https://quicktype.io

export interface BerriesListResponse {
    count: number;
    next: string;
    previous: null;
    results: Berry[];
}

export interface Berry {
    name: string;
    url: string;
}
